### PR TITLE
Driver Abstraction

### PR DESCRIPTION
**Pull request by abhirupa-tech**
Merge only after I whatsapp you

### CODE REVIEW

**Comment by A-Nikhil** [comment]
final commit done?

**Comment by abhirupa-tech** [comment]
Aren't there 9 commits on the PR?
22 hours is the time I made the PR, commits added on progressively. Last commit should be 'Unable to fix Errors'

**Comment by A-Nikhil** [comment]
Got it.. what files should I take?

**Comment by abhirupa-tech** [comment]
Take till the final commit, but it is advisable if you clone my repo and check the errors
and leave your repo, which is already working, untouched

**Pull request closed without merging**
